### ISSUE TITLE
Support `int.tryParse()`

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart2_constant#5]
It would be useful to have a polyfill for this:

```dart
int tryParse(String s) => int.parse(s, onError: (_) => null);
```

Maybe this package should have been named dart2_polyfill so that it could be more general :). 

cc @kwalrath @kevmoo

**Comment by kevmoo** [comment]
It's not really a polyfill unless we have extension methods.🤷‍♂️

I think we should leave this package as-is.

**Comment by chalin** [comment]
> I think we should leave this package as-is.

Yes, that is what I expected, but I figured that it was worth asking :)
